#!/usr/bin/env python3
"""Patch bitcrusher.rs with anti-aliased 2x oversampling and TPDF dither."""

with open('src/synth/bitcrusher.rs', 'r', encoding='utf-8') as f:
    c = f.read()

orig = c

# 1. Add prev_input and dither fields to struct
if 'prev_input: f32,' not in c:
    old = ('pub struct Bitcrusher {\n'
           '    pub bit_depth: f32,   // 1..16, 16=bypass\n'
           '    pub rate_crush: f32,  // 0..1, 0=bypass (sample rate reduction)\n'
           '    sample_hold: f32,\n'
           '    sample_counter: u32,  // integer counter for even timing\n'
           '    rate_period: u32,     // how many input samples per held sample\n'
           '    rng_state: u64,\n}')
    new = ('pub struct Bitcrusher {\n'
           '    pub bit_depth: f32,   // 1..16, 16=bypass\n'
           '    pub rate_crush: f32,  // 0..1, 0=bypass (sample rate reduction)\n'
           '    sample_hold: f32,\n'
           '    sample_counter: u32,  // integer counter for even timing\n'
           '    rate_period: u32,     // how many input samples per held sample\n'
           '    rng_state: u64,\n'
           '    // #2 — Anti-aliased oversampling: previous input for interpolation\n'
           '    prev_input: f32,\n'
           '    // TPDF dither toggle (default true)\n'
           '    pub dither: bool,\n}')
    if old in c:
        c = c.replace(old, new, 1)
        print("  applied struct fields")
    else:
        print(f"  FAIL struct patch. First 200 chars: {repr(c[:200])}")

# 2. Add prev_input and dither to with_seed init
if 'prev_input: 0.0,' not in c:
    old = ('        Self {\n'
           '            bit_depth: 16.0,\n'
           '            rate_crush: 0.0,\n'
           '            sample_hold: 0.0,\n'
           '            sample_counter: 0,\n'
           '            rate_period: 1,\n'
           '            rng_state: seed,\n'
           '        }')
    new = ('        Self {\n'
           '            bit_depth: 16.0,\n'
           '            rate_crush: 0.0,\n'
           '            sample_hold: 0.0,\n'
           '            sample_counter: 0,\n'
           '            rate_period: 1,\n'
           '            rng_state: seed,\n'
           '            prev_input: 0.0,\n'
           '            dither: true,\n'
           '        }')
    if old in c:
        c = c.replace(old, new, 1)
        print("  applied init patch")
    else:
        print("  FAIL init patch")

# 3. Replace the process method with anti-aliased version
if 'quantize(' not in c:
    old = ('    pub fn process(&mut self, x: f32) -> f32 {\n'
           '        // Bit crush (bypass at 16 bits)\n'
           '        let crushed = if self.bit_depth < 15.9 {\n'
           '            let levels = 2.0f32.powf(self.bit_depth.clamp(1.0, 16.0));\n'
           '            // Triangular dither: two uniform samples summed → triangular distribution\n'
           '            let d1 = (self.rng() - 0.5) / levels;\n'
           '            let d2 = (self.rng() - 0.5) / levels;\n'
           '            ((x * levels + d1 + d2).round()) / levels\n'
           '        } else {\n'
           '            x\n'
           '        };\n'
           '\n'
           '        // Rate crush (bypass at 0) — integer modulo for even timing\n'
           '        if self.rate_crush < 0.001 {\n'
           '            return crushed;\n'
           '        }\n'
           '        // Convert rate_crush [0,1] to a period: 1 = no crush, higher = more crush\n'
           '        let new_period = (1.0 / self.rate_crush.clamp(0.001, 1.0)).round() as u32;\n'
           '        if new_period != self.rate_period {\n'
           '            self.rate_period = new_period;\n'
           '            self.sample_counter = 0;\n'
           '        }\n'
           '        self.sample_counter += 1;\n'
           '        if self.sample_counter >= self.rate_period {\n'
           '            self.sample_counter = 0;\n'
           '            self.sample_hold = crushed;\n'
           '        }\n'
           '        self.sample_hold\n'
           '    }')
    new = ('    /// Quantize a sample to the given number of steps with optional TPDF dither.\n'
           '    fn quantize(&mut self, s: f32, steps: f32) -> f32 {\n'
           '        let dithered = if self.dither {\n'
           '            let lsb = 1.0 / steps;\n'
           '            let r1 = self.rng();\n'
           '            let r2 = self.rng();\n'
           '            s + (r1 - r2) * lsb\n'
           '        } else {\n'
           '            s\n'
           '        };\n'
           '        (dithered * steps).round() / steps\n'
           '    }\n'
           '\n'
           '    pub fn process(&mut self, x: f32) -> f32 {\n'
           '        // #2 — Anti-aliased bit crush via 2x oversampling.\n'
           '        // Two sub-samples are generated by linear interpolation between prev and\n'
           '        // current input, independently quantized, then averaged.\n'
           '        let crushed = if self.bit_depth < 15.9 {\n'
           '            let steps = 2.0f32.powi(self.bit_depth.clamp(1.0, 16.0) as i32 - 1);\n'
           '            let s0 = x;\n'
           '            let s1 = (x + self.prev_input) * 0.5;\n'
           '            let q0 = self.quantize(s0, steps);\n'
           '            let q1 = self.quantize(s1, steps);\n'
           '            0.5 * (q0 + q1)\n'
           '        } else {\n'
           '            x\n'
           '        };\n'
           '        self.prev_input = x;\n'
           '\n'
           '        // Rate crush (bypass at 0) — integer modulo for even timing\n'
           '        if self.rate_crush < 0.001 {\n'
           '            return crushed;\n'
           '        }\n'
           '        // Convert rate_crush [0,1] to a period: 1 = no crush, higher = more crush\n'
           '        let new_period = (1.0 / self.rate_crush.clamp(0.001, 1.0)).round() as u32;\n'
           '        if new_period != self.rate_period {\n'
           '            self.rate_period = new_period;\n'
           '            self.sample_counter = 0;\n'
           '        }\n'
           '        self.sample_counter += 1;\n'
           '        if self.sample_counter >= self.rate_period {\n'
           '            self.sample_counter = 0;\n'
           '            self.sample_hold = crushed;\n'
           '        }\n'
           '        self.sample_hold\n'
           '    }')
    if old in c:
        c = c.replace(old, new, 1)
        print("  applied process method")
    else:
        print("  FAIL process patch")

if c != orig:
    with open('src/synth/bitcrusher.rs', 'w', encoding='utf-8') as f:
        f.write(c)
    print("bitcrusher.rs patched OK")
else:
    print("No changes to bitcrusher.rs")
