//! Bitcrusher effect: bit-depth reduction and sample-rate crushing.
//!
//! At `bit_depth = 16` and `rate_crush = 0.0` the module is transparent.
//! Anti-aliased quantization uses 2x oversampling with linear interpolation;
//! dither uses TPDF noise to decorrelate quantization error from the signal.

/// Bitcrusher effect combining bit-depth reduction and sample-rate crushing.
///
/// Both effects are independent: set `bit_depth < 16` for quantization
/// artifacts and `rate_crush > 0` for sample-rate reduction.  TPDF dither
/// is applied before quantization when `dither = true` (default).
pub struct Bitcrusher {
    /// Quantization bit depth (1..16; 16 = bypass).
    pub bit_depth: f32,
    /// Sample-rate crush amount (0..1; 0 = bypass).
    pub rate_crush: f32,
    sample_hold: f32,
    sample_counter: u32,  // integer counter for even timing
    rate_period: u32,     // how many input samples per held sample
    rng_state: u64,
    // #2 — Anti-aliased oversampling: previous input for interpolation
    prev_input: f32,
    // TPDF dither toggle (default true)
    pub dither: bool,
}

impl Bitcrusher {
    /// Create a bitcrusher with default parameters and a fixed internal seed.
    pub fn new() -> Self {
        Self::with_seed(0xDEAD_BEEF_CAFE_BABE)
    }

    /// Construct with a caller-supplied seed so per-layer dither is decorrelated.
    pub fn with_seed(seed: u64) -> Self {
        Self {
            bit_depth: 16.0,
            rate_crush: 0.0,
            sample_hold: 0.0,
            sample_counter: 0,
            rate_period: 1,
            rng_state: seed,
            prev_input: 0.0,
            dither: true,
        }
    }

    /// xorshift64 — fast PRNG, returns [0, 1)
    fn rng(&mut self) -> f32 {
        self.rng_state ^= self.rng_state << 13;
        self.rng_state ^= self.rng_state >> 7;
        self.rng_state ^= self.rng_state << 17;
        let bits = 0x3F80_0000u32 | ((self.rng_state >> 41) as u32 & 0x007F_FFFF);
        f32::from_bits(bits) - 1.0
    }

    /// Quantize a sample to the given number of steps with optional TPDF dither.
    fn quantize(&mut self, s: f32, steps: f32) -> f32 {
        let dithered = if self.dither {
            let lsb = 1.0 / steps;
            let r1 = self.rng();
            let r2 = self.rng();
            s + (r1 - r2) * lsb
        } else {
            s
        };
        (dithered * steps).round() / steps
    }

    /// Process one audio sample and return the crushed output.
    ///
    /// Non-finite input is passed through unchanged; quantization and
    /// sample-hold operate only on finite values.
    pub fn process(&mut self, x: f32) -> f32 {
        // #2 — Anti-aliased bit crush via 2x oversampling.
        // Two sub-samples are generated by linear interpolation between prev and
        // current input, independently quantized, then averaged.
        let crushed = if self.bit_depth < 15.9 {
            let steps = 2.0f32.powi(self.bit_depth.clamp(1.0, 16.0) as i32 - 1);
            let s0 = x;
            let s1 = (x + self.prev_input) * 0.5;
            let q0 = self.quantize(s0, steps);
            let q1 = self.quantize(s1, steps);
            0.5 * (q0 + q1)
        } else {
            x
        };
        self.prev_input = x;

        // Rate crush (bypass at 0) — integer modulo for even timing
        if self.rate_crush < 0.001 {
            return crushed;
        }
        // Convert rate_crush [0,1] to a period: 1 = no crush, higher = more crush
        let new_period = (1.0 / self.rate_crush.clamp(0.001, 1.0)).round() as u32;
        if new_period != self.rate_period {
            self.rate_period = new_period;
            self.sample_counter = 0;
        }
        self.sample_counter += 1;
        if self.sample_counter >= self.rate_period {
            self.sample_counter = 0;
            self.sample_hold = crushed;
        }
        self.sample_hold
    }
}
